import Navigation from "./layout ui/navigation";
import "../globals.css";
import ContactUs from "./layout ui/contact-us";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "r/alevel",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <Navigation />
        {children}
        <ContactUs />
      </body>
    </html>
  );
}
