import Navigation from "./layout ui/navigation";
import "../globals.css";
import ContactUs from "./layout ui/contact-us";

export const metadata = {
  title: "r/alevel",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
        <ContactUs />
      </body>
    </html>
  );
}
