import type { Metadata } from "next";
import "../globals.css";
import Navigation from "./layout ui/navigation";
import ContactUs from "./layout ui/contact-us";
import { Poppins } from "next/font/google";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "r/alevel",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={poppins.className + " tracking-widest	"}>
        <Navigation />
        {children}
        <ContactUs />
      </body>
    </html>
  );
}
